/**
 GUEST='GUEST',
  USER='USER',
  ADMIN_DEP='ADMIN-DEP',
  ADMIN_ORG='ADMIN-ORG',
  ADMIN_SYS='ADMIN-SYS'
*/


export enum  UserTypeEnum{
  GUEST='GUEST',
  USER='USER',
  ADMIN_DEP='ADMIN-DEP',
  ADMIN_ORG='ADMIN-ORG',
  ADMIN_SYS='ADMIN-SYS'
  
}